# Generated by Django 5.2.6 on 2025-09-19 17:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=300)),
                ('tipo_servicio', models.CharField(choices=[('poda', 'Poda'), ('corte_cesped', 'Corte de césped'), ('limpieza', 'Limpieza y mantenimiento'), ('otros', 'Otros')], default='otros', max_length=30)),
                ('disponibilidad_horaria', models.CharField(blank=True, max_length=120)),
                ('metros_cuadrados', models.PositiveIntegerField()),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignada', 'Asignada'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('jardinero_asignado', models.CharField(blank=True, max_length=200, null=True)),
                ('hora_asignada', models.DateTimeField(blank=True, null=True)),
                ('token_confirmacion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
