# Generated by Django 5.2.6 on 2025-09-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jardinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
