# Generated by Django 5.2.6 on 2025-09-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0002_jardinero'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='calificacion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='foto_cliente',
            field=models.ImageField(blank=True, null=True, upload_to='solicitudes_fotos/'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('asignada', 'Asignada'), ('confirmada', 'Confirmada'), ('en_proceso', 'En proceso'), ('pendiente_evaluacion', 'Pendiente de evaluación'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=30),
        ),
    ]
